#!/bin/sh
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Define allowed branch name format
if ! echo "$branch_name" | grep -qE "^(feat|fix|test|chore)/[a-z0-9._-]+$"; then
    echo " Invalid branch name: '$branch_name'."
    echo " Allowed format: <type>/<description> (e.g., feat/new-feature)"
    echo " Allowed types: feat, fix, test, chore."
    exit 1
fi

echo " Branch name '$branch_name' is valid"
exit 0